### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by ofirkris** [lyndonzheng/TFill#1]
Hello great research! any specific timeline for when you're planning to release the code?

**Comment by lyndonzheng** [comment]
Hi @ofirkris, thanks for your interest. We originally plan to release the model last month. But the paper is rejected in the ICCV2021. Therefore, we still keep on discussing how to process this project. Once we decide, we may have the timeline to release the code and corresponding model. I would like to release the model as soon as possible, but it still depends on the sponsor.
