### ISSUE TITLE
Issue on BaseModel

### ISSUE THREAD

**Issue by JiaqiongLi** [lyndonzheng/TFill#4]
Thanks for releasing the code. 
During installing the code, I met a small problem with the base model. The notification is "In model.base_model.py, there should be a subclass of BaseModel with class name that matches base in lowercase.". Could you kindly tell me how to fix it? I really appreciate it.

**Comment by puzhou-wrj** [comment]
你好，我也遇到过相似的问题，可以检查你的model的py文件，看看里面Class定义的model名称和bug中的提示model名称是否对得上。

**Comment by Ellohiye** [comment]
> 你好，我也遇到过相似的问题，可以检查你的model的py文件，看看里面Class定义的model名称和bug中的提示model名称是否对得上。

请问你是怎么解决的呀

**Comment by Ellohiye** [comment]
> Thanks for releasing the code. During installing the code, I met a small problem with the base model. The notification is "In model.base_model.py, there should be a subclass of BaseModel with class name that matches base in lowercase.". Could you kindly tell me how to fix it? I really appreciate it.

你好，请问你最后解决了吗？可以教教我吗非常感谢
