### ISSUE TITLE
About the training of models applied to 256*256 resolution images

### ISSUE THREAD

**Issue by ScarletBlaze** [lyndonzheng/TFill#7]
Thank you for sharing your wonderful work. We would like to use your model as a baseline, but due to the difference in training settings, the direct application of the model parameters you provided to 256*256 images would not yield particularly good results.  So we would like to train a TFill for a 256*256 image version, can you give us some advice on the training settings regarding the model?

**Comment by lyndonzheng** [comment]
Hi @ScarletBlaze, you can directly used the coarse results in the first stage for $256\times256$ resolution, which provide high qualitative results for both object removal and foreground completion.

**Comment by 1997Jessie** [comment]
> Hi @ScarletBlaze, you can directly use the coarse results in the first stage for 256×256 resolution, which provide high qualitative results for both object removal and foreground completion.

Hi,@lyndonzheng ,I wanna train images about 1024*768 resolution ,I don't know about revising --load_size、 --fine_size and --fixed_size to make training best

**Comment by 1997Jessie** [comment]
> Hi @ScarletBlaze, you can directly use the coarse results in the first stage for 256×256 resolution, which provide high qualitative results for both object removal and foreground completion.

Looking forward to your reply~
