### ISSUE TITLE
Same outputs for multiple  results

### ISSUE THREAD

**Issue by Jackieqfh143** [lyndonzheng/TFill#9]
When testing the model on CelebA-HQ dataset, we got exactly same outputs for multiple  results. Is there anything wrong?

**Comment by lyndonzheng** [comment]
Hi @Jackieqfh143 For existing models, we do not provide multiple and diverse results as our previous [PIC](https://github.com/lyndonzheng/Pluralistic-Inpainting). Our improved version provides the multiple results using VQ, but it is still under review. Therefore, we do not update the corresponding code and model.

**Comment by Jackieqfh143** [comment]
Okay. Thanks for your reply!
